2025-08-19 01:53:14,358 - pyftpdlib - INFO - concurrency model: async
2025-08-19 01:53:14,359 - pyftpdlib - INFO - masquerade (NAT) address: None
2025-08-19 01:53:14,359 - pyftpdlib - INFO - passive ports: None
2025-08-19 01:53:14,359 - pyftpdlib - INFO - >>> starting FTP server on 0.0.0.0:2120, pid=26652 <<<
2025-08-19 01:57:06,683 - RouterManager - INFO - Node cloud1 started, checking for pending files
2025-08-19 01:57:24,986 - RouterManager - INFO - Node node1 started, checking for pending files
2025-08-19 02:19:46,645 - pyftpdlib - INFO - >>> shutting down FTP server, 0 socket(s), pid=26652 <<<
2025-08-19 02:19:46,646 - RouterManager - INFO - FTP server stopped for 127.0.0.1
2025-08-19 02:19:46,647 - RouterManager - INFO - Socket server stopped for 127.0.0.1
2025-08-19 02:19:46,647 - RouterManager - ERROR - Socket server error: [WinError 10038] An operation was attempted on something that is not a socket
Traceback (most recent call last):
  File "E:\cloud-architecture-simulation\router_manager.py", line 75, in _handle_socket_connections
    except Exception as e:
  File "C:\Users\JUAN MIKE\.conda\envs\Cloudsim\lib\socket.py", line 293, in accept
    fd, addr = self._accept()
OSError: [WinError 10038] An operation was attempted on something that is not a socket
2025-08-19 02:19:49,607 - pyftpdlib - INFO - concurrency model: async
2025-08-19 02:19:49,607 - pyftpdlib - INFO - masquerade (NAT) address: None
2025-08-19 02:19:49,608 - pyftpdlib - INFO - passive ports: None
2025-08-19 02:19:49,608 - pyftpdlib - INFO - >>> starting FTP server on 0.0.0.0:2120, pid=25864 <<<
2025-08-19 02:19:53,947 - RouterManager - INFO - Node cloud1 started, checking for pending files
2025-08-19 02:19:58,794 - RouterManager - INFO - Node node1 started, checking for pending files
2025-08-19 02:20:35,603 - RouterManager - INFO - Node cloud1 started, checking for pending files
